SELECT 
    YEAR(DATE) AS VALUATION_YEAR,
    METRO,
    INDICATOR_ID,
    ROUND(AVG(HOME_VALUE),2) AS AVG_HOME_VALUE
FROM  
    {{ref('silver_zillow_home_values_metros')}}
GROUP BY 
    METRO,
    INDICATOR_ID,
    VALUATION_YEAR
ORDER BY 
    METRO,
    INDICATOR_ID,
    VALUATION_YEAR DESC